version: "2"

services:
  redis:
    image: redis:latest
  react-app:
    image: node:latest
    ports: 
      - "3000:3000"
    environment: 
      REDIS_URL: redis
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev